backstage:
  image:
    registry: localhost:5000
    repository: backstage-backend
    tag: local
    pullPolicy: Always

  startupProbe:
    failureThreshold: 30
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 2

  # Allow to declare extra env vars on pod
  extraEnvVars:
    - name: BACKSTAGE_ENV
      value: k3d
    - name: K8S_TOKEN
      valueFrom:
        secretKeyRef:
          name: k3d-admin-token
          key: token

  args:
    - "--config"
    - "app-config.yaml"
    - "--config"
    - "app-config.production.yaml"

  # Create an backstage-app-config config-maps (used by the frontend as well)
  appConfig:
    app:
      title: Backstage
      baseUrl: http://backstage.localhost:8080
    backend:
      baseUrl: http://backstage.localhost:8080
      listen:
        port: 7007
        host: 0.0.0.0
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: 'true'
    catalog:
      locations:
        - type: url
          target: https://github.com/MozeBaltyk/backstage/blob/master/common/entities/guest.yaml
          rules:
            - allow: [User, Group]
        - type: url
          target: https://github.com/MozeBaltyk/backstage/blob/master/common/entities/k8s-entities.yaml
          rules:
            - allow: [Component]
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - url: https://kubernetes.default.svc
              name: k3d-mycluster
              authProvider: 'serviceAccount'
              serviceAccountToken: ${K8S_TOKEN}
              skipTLSVerify: true
              skipMetricsLookup: true

  podSecurityContext:
    runAsUser: 65532
    runAsNonRoot: true
    fsGroup: 65532

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  extraVolumes:
    - name: tmp
      emptyDir: {}

  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp

# Postgre Block 
postgresql:
  # -- Switch to enable or disable the PostgreSQL helm chart
  enabled: true
  # -- The authentication details of the Postgres database
  auth:
    username: backstage
    password: backstagepassword
    postgresPassword: adminpassword

extraDeploy:
  # -----------------------------
  # Frontend Deployment
  # -----------------------------
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backstage-frontend
      labels:
        app: backstage-frontend
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: backstage-frontend
      template:
        metadata:
          labels:
            app: backstage-frontend
        spec:
          securityContext:
            runAsUser: 65532
            runAsNonRoot: true

          # use same configmaps than backend
          volumes:
            - name: app-config-volume
              configMap:
                name: backstage-app-config
                items:
                  - key: app-config.yaml
                    path: app-config.yaml

          containers:
            - name: frontend
              image: localhost:5000/backstage-frontend:local
              imagePullPolicy: Always
              # env:
              #   - name: APP_CONFIG_app_title
              #     value: Backstage
              #   - name: APP_CONFIG_app_baseUrl
              #     value: https://backstage.io
              #   - name: APP_CONFIG_backend_baseUrl
              #     value: https://backstage.io

              # use same configmaps than backend
              volumeMounts:
                - name: app-config-volume
                  mountPath: /etc/app-config.yaml
                  readOnly: true
                  subPath: app-config.yaml  # optional: mount as a file

              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              ports:
                - name: http
                  containerPort: 8080
              # env:
              #   - name: PORT
              #     value: "3000"
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 5
                periodSeconds: 10
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 20

  # -----------------------------
  # Frontend Ingress
  # -----------------------------
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: backstage-ingress
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/router.tls: "false"
    spec:
      ingressClassName: traefik
      rules:
        - host: backstage.localhost
          http:
            paths:
              - path: /api
                pathType: Prefix
                backend:
                  service:
                    name: backstage
                    port:
                      number: 7007

              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: backstage-frontend
                    port:
                      number: 3000

  # -----------------------------
  # Frontend Service
  # -----------------------------
  - apiVersion: v1
    kind: Service
    metadata:
      name: backstage-frontend
    spec:
      type: ClusterIP
      selector:
        app: backstage-frontend
      ports:
        - name: http-frontend
          port: 3000
          targetPort: 8080

  # -----------------------------
  # Token Secret for K3D Cluster Access
  # -----------------------------
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: k3d-admin

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: svca-admin
    roleRef:
      kind: ClusterRole
      name: cluster-admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: k3d-admin
        namespace: backstage

  - apiVersion: v1
    kind: Secret
    metadata:
      name: k3d-admin-token
      annotations:
        kubernetes.io/service-account.name: k3d-admin
    type: kubernetes.io/service-account-token
