name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  security-events: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CONTEXT_DIR: vanilla

jobs:
  build-scan:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - name: backstage-backend
            dockerfile: Containerfile.backend
          - name: backstage-frontend
            dockerfile: Containerfile.frontend

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Build image
      - name: Build ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_DIR }}
          file: ${{ env.CONTEXT_DIR }}/${{ matrix.dockerfile }}
          load: true
          push: false
          tags: ${{ matrix.name }}:${{ github.sha }}

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.69.2

      # Scan image
      - name: Scan ${{ matrix.name }}
        uses: aquasecurity/trivy-action@0.34.2
        with:
          scan-type: "image"
          image-ref: ${{ matrix.name }}:${{ github.sha }}
          format: sarif
          output: trivy-${{ matrix.name }}.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      # Upload SARIF
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-${{ matrix.name }}.sarif

      # Failed if vulnerabilities are found
      - name: Enforce vulnerability policy
        uses: aquasecurity/trivy-action@v0.34.2
        with:
          scan-type: "image"
          image-ref: ${{ matrix.name }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
          skip-setup-trivy: true
