name: Release Backstage
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_TAG: ${{ github.ref_name }}
  REGISTRY: ghcr.io/mozebaltyk
  CONTEXT_DIR: vanilla

jobs:
  build-push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: backstage-backend
            dockerfile: Containerfile.backend
          - name: backstage-frontend
            dockerfile: Containerfile.frontend

    steps:
      - uses: actions/checkout@v6

      - name: Build & Push ${{ matrix.name }}
        uses: docker/github-builder/.github/workflows/build.yml@v1
        permissions:
          id-token: write
          packages: write
        with:
          output: image
          push: true
          platforms: linux/amd64,linux/arm64
          runner: amd64
          setup-qemu: true
          file: ${{ env.CONTEXT_DIR }}/${{ matrix.dockerfile }}
          context: ${{ env.CONTEXT_DIR }}
          sbom: true
          set-meta-labels: true
          set-meta-annotations: true
          meta-images: |
            ${{ env.REGISTRY }}/${{ matrix.name }}
          meta-tags: |
            type=ref,event=tag
            ${{ github.ref_name }}
            latest
        secrets:
          registry-auths: |
            - registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
